### ISSUE TITLE
Create a CKAN theme that implements the Italia Design Guidelines 

### ISSUE THREAD

**Issue by ruphy** [italia/design-ckan-theme#1]
Create a theme for CKAN based on the [User Interface design guidelines](
https://design-italia.readthedocs.io/it/stable/doc/user-interface.html).

Do include [the design web toolkit](https://github.com/italia/design-web-toolkit) as a dependency, and make sure you write your code in a way which is generic enough so that, later on, it be replaced by another toolkit (e.g. bootstrap) without too much effort.

Some example websites with the correct style
https://developers.italia.it
https://designers.italia.it

**Comment by piersoft** [comment]
Credo di essere a buon punto. domani committo o scrivo qui alcuni commenti su quello che ho fatto.
Potete vedere il docker Agid personalizzato secondo User Interface design guidelines cliccando [QUI](http://www.piersoft.it/ckan/)

**Comment by ruphy** [comment]
Waiting for a PR :slightly_smiling_face:

**Comment by piersoft** [comment]
that's all folks :) 

https://github.com/piersoft/designckan

**Comment by ruphy** [comment]
fixed by #2
